project:
  type: website
  output-dir: docs

website:
  title: "Hendrik Mahlkow"
  navbar:
    title: false # change this to false!
    left:
      - href: index.qmd
        text: Hendrik Mahlkow
      - about.qmd
      - coding.qmd
      - research.qmd
  search: false # no search bar!
  page-footer: 
    background: light
    left: 
    # add the current date to the footer
      - "Updated on {{< meta date >}}. © Hendrik Mahlkow 1989-2023."
    right: 
      - icon: github
        href: https://github.com/hendrikmahlkow
      - icon: twitter
        href: https://twitter.com/HMahlkow

format:
  html:
    # see: https://quarto.org/docs/output-formats/html-themes.html#customizing-themes
    theme: [litera, styles.scss] 
    mainfont: Jost
    css: styles.css

editor: visual

