---
title: "CV"
# script to highlight text in the body and to parse date to footer
include-in-header:
  text: |
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        document.body.innerHTML = document.body.innerHTML.replace(/==([^=]+)==/g, '<span class="highlight">$1</span>');
      });
    </script>
---

I am an economist specializing in international trade and climate change. I am deputy head of the Trade Policy research group at the ==Kiel Institute for the World Economy== and a postdoctoral researcher at ==Kiel University==. I hold a Ph.D. in Quantitative Economics from ==Christian-Albrechts-Universität zu Kiel==. I studied Agricultural Economics (M.Sc.) and Agricultural Science (B.Sc.) at ==Humboldt-Universität zu Berlin==. During my PhD, I visited the ==University of California, Berkeley==. From 2022 to 2025, I was a Fellow of the ==Joachim Herz Foundation==.

### Current Positions

|        |                                                                                         |
|--------|-----------------------------------------------------------------------------------------|
| 2026 - | **Kiel Institute for the World Economy**, Deputy Head of the Trade Policy Research Group |
| 2026 - | **Kiel University**, Postdoctoral Researcher                                            |
| 2026 - | **Austrian Institute of Economic Research (WIFO)**, Research Associate                   |
| 2020 - | **Independent Consultant**, Programmer, & Data Scientist                                 |

### Previous Positions

|             |                                                            |
|-------------|------------------------------------------------------------|
| 2024 - 2026 | **Kiel Institute for the World Economy**, Researcher       |
| 2023 - 2025 | **Austrian Institute of Economic Research**, Economist     |
| 2019 - 2023 | **Kiel Institute for the World Economy**, Junior Economist |

### Education

|             |                                                                  |
|-------------|------------------------------------------------------------------|
| 2019 - 2024 | **Kiel University**, PhD in Quantitative Economics               |
| 2022 - 2023 | **University of California, Berkeley**, Visiting PhD Student     |
| 2014 - 2018 | **Humboldt University of Berlin**, MSc in Agricultural Economics |
| 2009 - 2012 | **Humboldt University of Berlin**, BSc in Agricultural Sciences  |

### **Other relevant experience**

|             |                                                             |
|-------------|-------------------------------------------------------------|
| 2017 - 2018 | **Potsdam Institute (PIK)**, Intern Land Use and Resilience |

[Download CV](/files/CV.pdf)
