---
title: "Research"
# script to highlight text in the body and to parse date to footer
include-in-header:
  text: |
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        document.body.innerHTML = document.body.innerHTML.replace(/==([^=]+)==/g, '<span class="highlight">$1</span>');
      });
    </script>
---

### **Publications**

-   [**Macroeconomic structural change likely increases inequality in India more than climate policy**](https://www.doi.org/10.1088/1748-9326/ad34e9) (with Marian Leimbach, Michael Hübler, Lorenzo Montrone, Gabriel Felbermayr, Mathias Kalkuhl, Jan Steckel, Eduard Bukin, Johannes Koch, Marcos Marcolino, & Frank Pothen) *Environmental Research Letters*, 2024.

-   [**Long-Run Impacts of the Conflict in Ukraine on Food Security in Africa**](http://doi.org/10.1111/1467-8268.12745), (with Lacina Balma, Tobias Heidland, Sebastian Jävervall, Adamon N. Mukasa and Andinet Woldemichael) *African Development Review*, 2024.

-   [**Cutting through the Value Chain: The Long-Run Effects of Decoupling the East from the West**](https://www.ifw-kiel.de/de/publikhttps://link.springer.com/article/10.1007/s10663-022-09561-wationen/kieler-arbeitspapiere/2022/cutting-through-the-value-chain-the-long-run-effects-of-decoupling-the-east-from-the-west-17087/) (with Gabriel Felbermayr and Alexander Sandkamp), *Empirica*, 2023.

### **Working Paper**

-   [**Quantitative Trade with Ships**](https://www.kielinstitut.de/de/publikationen/quantitative-trade-with-ships-19579/) (with Sonali Chowdhry and Inga Heiland), 2026.

-   [**Tariffs Hit Differently: The Regional Impact of US Tariffs across Europe and the Role of the Single Market**](https://www.kielinstitut.de/de/publikationen/tariffs-hit-differently-the-regional-impact-of-us-tariffs-across-europe-and-the-role-of-the-single-market-19225/) (with Julian Hinz and Joschka Wanner), 2025.

-   [**The KITE Model Suite: A Quantitative Framework for International Trade Analysis**](https://trade.ifw-kiel.de/KTTM/KITE_whitepaper.pdf) (with Gabriel Felbermayr, Julian Hinz, Sebastian Krantz, and Joschka Wanner), 2025.

-   [**The Carbon Footprint of Global Trade Imbalances**](https://www.cesifo.org/en/publications/2023/working-paper/carbon-footprint-global-trade-imbalances) (with Joschka Wanner), *CESifo*, 2023.
